#!/bin/bash
echo "🔐 Verificação de Senha PostgreSQL"
echo "=================================="
echo ""
echo "O erro indica que a senha do PostgreSQL está incorreta."
echo ""
echo "📝 Seu arquivo .env atual tem:"
grep "POSTGRES_PASSWORD" /opt/qsdpharma/.env || echo "❌ POSTGRES_PASSWORD não encontrada!"
echo ""
echo "⚙️  Opções:"
echo ""
echo "1️⃣  Usar senha padrão do exemplo:"
echo "   Edite o .env e defina:"
echo "   POSTGRES_PASSWORD=MUDE_ESTA_SENHA_PARA_ALGO_FORTE_E_SEGURO"
echo ""
echo "2️⃣  Ou use uma senha personalizada:"
echo "   Edite o .env com uma senha forte"
echo ""
echo "📝 Para editar:"
echo "   nano /opt/qsdpharma/.env"
echo ""
echo "🔄 Depois de editar, rode:"
echo "   cd /opt/qsdpharma"
echo "   docker-compose -f docker-compose.production.yml down -v"
echo "   docker-compose -f docker-compose.production.yml up -d"
